version: "3.9"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db.cfc101.click
      WORDPRESS_DB_USER: cfc101
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ~/wordpress/html:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
        - ~/sessions
    ports:
        - 40000:80
    restart: always
    environment:
        PMA_HOST: db.cfc101.click
        PMA_USER:
        PMA_PASSWORD:


volumes:
  db_data:
