version: "3.9"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 
      WORDPRESS_DB_USER: 
      WORDPRESS_DB_PASSWORD: 
      WORDPRESS_DB_NAME: 
    volumes:
      - ~/wordpress/html:/var/www/html

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      volumes:
          - ~/sessions
      ports:
          - 40000:80
      environment:
          PMA_HOST: 
          PMA_USER: 
          PMA_PASSWORD: 


volumes:
  db_data:

