version: "3.9"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db.chi-sin.link
      WORDPRESS_DB_USER: cfc101
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ~/wordpress/html:/var/www/html

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      volumes:
          - ~/sessions
      ports:
          - 40000:80
      environment:
          PMA_HOST: cfc101
          PMA_USER: wordpress
          PMA_PASSWORD: wordpress


volumes:
  db_data:

